### ISSUE TITLE
N-API warning

### ISSUE THREAD

**Issue by staltz** [hyperswarm/hyperswarm#10]
I ran [`example-s.js`](https://github.com/staltz/multiserver-dht/tree/hyperswarm) in `multiserver-dht` on branch `hyperswarm`, with node v8.11.1, and got the error:

```
(node:11413) Warning: N-API is an experimental feature and could change at any time.
node: symbol lookup error: ./multiserver-dht/node_modules/@hyperswarm/network/node_modules/utp-native/prebuilds/linux-x64/node-napi.node: undefined symbol: napi_fatal_exception
```

If node v10 is a requirement, then that could be added to `engines` in package.json.

**Comment by mafintosh** [comment]
Is that latest 8? It’ll work in anything above 6 but some 8 versions print the warning

**Comment by mafintosh** [comment]
(It might be that all 8 versions do)

**Comment by staltz** [comment]
Interesting, it works on v8.12.0. ("Works" means that this error does not occur but I see error #11 instead) Would still be good to add the compatible engines in package.json

**Comment by mafintosh** [comment]
It's compatible with any version of 8 it just prints the error in earlier versions but yea we should specify that :)
