### ISSUE TITLE
Can't connect on two topics to same peer

### ISSUE THREAD

**Issue by bplaster** [hyperswarm/hyperswarm#14]
I noticed that in `Queue.push`, the `id` is defined as `const id = peer.host + ':' + peer.port`, which means that a peer can't connect to the same peer on two different topics. Is there anyway, similar to discovery-swarm, that we can make it such that the `id` is based on the topic? 

Something like:
`const id = peer.host + ':' + peer.port + '@' + peer.topic.toString('hex')`

**Comment by fedpettinella** [comment]
This is a fair point. Alternatively the ports could be cycled for different
topics

**Comment by mafintosh** [comment]
This is fixed
