### ISSUE TITLE
UPNP support

### ISSUE THREAD

**Issue by RangerMauve** [hyperswarm/hyperswarm#29]
I think it'd be useful to integrate [UPNP](https://en.wikipedia.org/wiki/Universal_Plug_and_Play) into the stack so that we can leverage it on home networks without needing to think as much about the hole punching.

Does [node-nat-upnp](https://github.com/indutny/node-nat-upnp) do the trick?

Is there any reason UPNP would be a bad idea?

**Comment by mafintosh** [comment]
Only to avoid having too many “moving parts”. Do you have any data/links on networks where upnp work but udp hole punching doesnt?

**Comment by RangerMauve** [comment]
Nope! I don't have any data on how well hole punching works either, tbh. 😅

A question about the hole punching while you're here, does it rely on known 3rd party servers, or is it any peer in the DHT?

The reason I ask is that UPNP could be an improvement over known servers since they can be inaccessible on certain networks (e.g. issues with Chinese Dat users and the DNS trackers)

**Comment by mafintosh** [comment]
Hole punching works over any peer. One of the innovations in Hyperswarm 😊. If adding upnp is trivial open a pr and we can test it next time hole punching fails

**Comment by RangerMauve** [comment]
Sweet! If hole punching does the trick then UPNP will just complicate things. I'll close this for now and reopen if there's data on it helping anything. 😁
