### ISSUE TITLE
Emit event when a peer you've already connected to is found for another topic

### ISSUE THREAD

**Issue by RangerMauve** [hyperswarm/hyperswarm#33]
Some peers will be advertising on multiple topics that you both share. Instead of establishing a new connection to that peer per topic, it'd be useful to let the application optionally multiplex existing connections.

For example, if I subscribe to topic `foo`, and find a peer, then subscribe to topic `bar`, and find that same peer again, I'd like to be able to ask peer for `bar` over our `foo` connection instead of establishing a new tunnel.

This should help for applications like [collaborative editors](https://github.com/inkandswitch/pushpin) that might have a large amount of hyperdrives or hypercores shared between a few peers.

cc @pvh

**Comment by mafintosh** [comment]
Yep, we are already working on this - should land soon

**Comment by RangerMauve** [comment]
Any updates?

**Comment by mafintosh** [comment]
got released
