### ISSUE TITLE
Autoconnect flag

### ISSUE THREAD

**Issue by RangerMauve** [hyperswarm/hyperswarm#37]
It'd be nice to be able to disable the auto-connection feature for cases where it'd be handy to control that at the application level.

**Comment by mafintosh** [comment]
You can do that today using the info object. I think the method is info.reconnect(false)

**Comment by RangerMauve** [comment]
How do I get the info object from a swarm instance?

**Comment by RangerMauve** [comment]
Oh, I think I get it. When I get the `peer` event, that's where I'd invoke `info.reconnect(false)` which would prevent the initial connection?

**Comment by indutny** [comment]
Except that you don't have `info` in `peer` event :joy:

**Comment by mafintosh** [comment]
@indutny ah you wanna configure peer stuff before a connection happens?

**Comment by indutny** [comment]
I probably don't. Was just browsing through the issues to see if there is anything useful for my case.

**Comment by mafintosh** [comment]
you use the companion object next to the connection in the 'connection' event to manage all this
