### ISSUE TITLE
Add ability to load peers to use as bootstrap nodes

### ISSUE THREAD

**Issue by cblgh** [hyperswarm/hyperswarm#48]
To increase the resilience of using hyperswarm (e.g. networks being forcefully shut off, or booting into a specifically set up mesh network) it would be very useful if peers could somehow load in a list of IPs to use as introducers/bootstrap nodes for the network. Either that or just peers to connect to in general.

Similarly it would be very useful to export a list of the currently connected peers.

This has been discussed previously in
* toronto mesh would like to be able to pass in a list of ipv6 addresses https://github.com/cabal-club/cabal-cli/issues/113#issuecomment-514814400 (related issue of supporting ipv6 in hyperswarm https://github.com/hyperswarm/dht/issues/1)

**Comment by mafintosh** [comment]
You can pass your own bootstrap list already using the dht options. Let me see if we expose nodes atm

**Comment by cblgh** [comment]
sweet! yeah exporting would be 👍

**Comment by mafintosh** [comment]
This landed in master with dht.getNodes, dht.addNodes

**Comment by cblgh** [comment]
heyyyy fantastic!
