### ISSUE TITLE
Why Socket Auto Closed After Send Data

### ISSUE THREAD

**Issue by xctest** [hyperswarm/hyperswarm#52]
#### this is my swarm configuration:
```.
const swarm = hyperswarm({
    ephemeral: false,
})
swarm.join(topic, {
    lookup: true,
     announce: true
})
// i use end to send data
socket.end(someText)
```

#### any help is appreciated!

**Comment by davidmarkclements** [comment]
if you don't want a socket to close, don't use `end` to send data, use `write`

https://nodejs.org/api/net.html#net_socket_end_data_encoding_callback
https://nodejs.org/api/net.html#net_socket_write_data_encoding_callback
