### ISSUE TITLE
Does this encrypt connections?

### ISSUE THREAD

**Issue by cinnamon-bun** [hyperswarm/hyperswarm#65]
Are connections between peers encrypted by hyperswarm?

If not, does dat put its own layer of encryption on top of these peer streams?

**Comment by RangerMauve** [comment]
Hyperswarm doesn't encrypt connections, Dat uses the NOISE protocol for transport level encryption

**Comment by mafintosh** [comment]
Noise is used in hypercore-protocol for peer authentication and an xsalsa20 stream is afterwards used for the actual encryption to be 100% correct. Hyperswarm itself provides no encryption, just raw connections. Up to the consumer to layer that on top (as the consumer knows how to authenticate peers etc etc)
