### ISSUE TITLE
Duplicate messages between connected servers

### ISSUE THREAD

**Issue by draeder** [hyperswarm/hyperswarm#72]
I'm a little confused, and I apologize if it shows my ignorance/lack of experience. 

I am trying to send a message from one connected node server to the other using:

```
  // you can now use the socket as a stream, eg:
    process.stdin.pipe(socket).pipe(process.stdout)
```

The problem is the message from one terminal is duplicated on the other. 

For example, if I type the following in serverA:
```
test 123
```

I get the following in serverB:
```
test 123
test 123
```

. . . and vice versa

I can work around this by setting one of the two servers to not announce:
```
swarm.join(topic, {
  lookup: true, // find & connect to peers
  announce: false // <--------- don't announce, stops duplicates
})
```

**Comment by draeder** [comment]
I was able to solve this thanks to the code in example.js.

**Comment by jamesfiltness** [comment]
Could I ask which code specifically in example.js help you fix this issue?

**Comment by draeder** [comment]
@jamesfiltness 

```js
  if (client) process.stdin.pipe(socket) // client processes the message
```

or

```js
  if (!client) process.stdin.pipe(socket) // server processes the message
```

**Comment by james-filtness** [comment]
thanks!
