### ISSUE TITLE
Hyperswarm in the browser?

### ISSUE THREAD

**Issue by draeder** [hyperswarm/hyperswarm#74]
Hyperswarm is great for node servers, but is there a way to use it in the browser?

**Comment by tinchoz49** [comment]
Hi @draeder, there is already an open issue about this: https://github.com/hyperswarm/hyperswarm/issues/62

You can use: https://github.com/RangerMauve/hyperswarm-web

**Comment by draeder** [comment]
@tinchoz49 Thanks
